[Icon Theme]
Name=__THEME_NAME__-Icons
Comment=Java Net Lava OS Icon Theme
Inherits=Adwaita,Papirus
Directories=scalable/apps,scalable/categories,scalable/devices,scalable/mimetypes,scalable/places,scalable/status,scalable/actions

[scalable/apps]
Size=48
MinSize=16
MaxSize=512
Context=Apps
Type=Scalable

[scalable/categories]
Size=48
MinSize=16
MaxSize=512
Context=Categories
Type=Scalable

[scalable/devices]
Size=48
MinSize=16
MaxSize=512
Context=Devices
Type=Scalable

[scalable/mimetypes]
Size=48
MinSize=16
MaxSize=512
Context=MimeTypes
Type=Scalable

[scalable/places]
Size=48
MinSize=16
MaxSize=512
Context=Places
Type=Scalable

[scalable/status]
Size=48
MinSize=16
MaxSize=512
Context=Status
Type=Scalable

[scalable/actions]
Size=48
MinSize=16
MaxSize=512
Context=Actions
Type=Scalable
