title    Java Net Lava OS (%ARCH%, UEFI) with speech
sort-key 02
linux    /%INSTALL_DIR%/boot/%ARCH%/vmlinuz-linux-lts
initrd   /%INSTALL_DIR%/boot/%ARCH%/initramfs-linux-lts.img
options  archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% accessibility=on nvidia_drm.modeset=1 nvidia_drm.fbdev=1 plymouth.enable=0 systemd.show_status=1
