[Icon Theme]
Name=JNL OS Tech
Comment=JNL OS technology-themed icon set
Inherits=Adwaita
Directories=scalable/apps,scalable/places,scalable/categories,scalable/devices,scalable/mimetypes,scalable/status,scalable/actions,48x48/apps,256x256/apps,128x128/apps,64x64/apps,32x32/apps,24x24/apps,16x16/apps

[scalable/apps]
Size=48
Type=Scalable
Context=Applications

[scalable/places]
Size=48
Type=Scalable
Context=Places

[scalable/categories]
Size=48
Type=Scalable
Context=Categories

[scalable/devices]
Size=48
Type=Scalable
Context=Devices

[scalable/mimetypes]
Size=48
Type=Scalable
Context=MimeTypes

[scalable/status]
Size=48
Type=Scalable
Context=Status

[scalable/actions]
Size=48
Type=Scalable
Context=Actions

[48x48/apps]
Size=48
Type=Fixed
Context=Applications

[256x256/apps]
Size=256
Type=Fixed
Context=Applications

[128x128/apps]
Size=128
Type=Fixed
Context=Applications

[64x64/apps]
Size=64
Type=Fixed
Context=Applications

[32x32/apps]
Size=32
Type=Fixed
Context=Applications

[24x24/apps]
Size=24
Type=Fixed
Context=Applications

[16x16/apps]
Size=16
Type=Fixed
Context=Applications
